   'NGANHANGBENB': 'Ngân hàng Bên B',
   'NGAN_HANG_A': 'Ngân hàng Bên A',
   'NGAN_HANG_B': 'Ngân hàng Bên B',
   'NGAY_HD': 'Ngày ký hợp đồng',
   'THANG_HD': 'Tháng ký hợp đồng',
   'NAM_HD': 'Năm ký hợp đồng',
   'NGAY_HOPDONG': 'Ngày ký hợp đồng',
   'THANG_HOPDONG': 'Tháng ký hợp đồng',
   'NAM_HOPDONG': 'Năm ký hợp đồng',
   'NGAYKYHOPDONG': 'Ngày ký hợp đồng',
   'SO_HD': 'Số hợp đồng',
   'SO_HOPDONG': 'Số hợp đồng',
   'SOHOPDONG': 'Số hợp đồng',
   'SOHD': 'Số hợp đồng',
   'NGAY_BAT_DAU': 'Ngày bắt đầu',
   'NGAY_KET_THUC': 'Ngày kết thúc',
   'BANGCHUGIATRI': 'Bằng chữ giá trị',
   'BANGGIATRIHOPDONG': 'Bảng giá trị hợp đồng',
   'BANG_GIATRIHOPDONG': 'Bảng giá trị hợp đồng',
   'GIATRIHOPDONG': 'Giá trị hợp đồng',
   'TEN_CTY_VIET_TAT': 'Tên công ty viết tắt',
   'NOI_KY': 'Nơi ký',
   'DIA_DIEM': 'Địa điểm',
   'BANG_GIATRITHUEXE': 'Bảng giá trị thuê xe',
   'BANGGIATRITHUEXE': 'Bảng giá trị thuê xe',
   'GOI_THAU': 'Gói thầu',
   'TEN_CONGTRINH': 'Tên công trình',
   'BEN_DE_NGHI': 'Bên đề nghị (Bên B)',
   'BEN_DUOC_DE_NGHI': 'Bên được đề nghị (Bên A)',
   'DAI_DIEN_BEN_DE_NGHI': 'Đại diện bên đề nghị (Bên B)',
   'STK_BEN_DE_NGHI': 'Số tài khoản bên đề nghị (Bên B)',
   'NGAN_HANG_BEN